### ISSUE TITLE
typo in site/build.sbt

### ISSUE THREAD

**Issue by toreller** [Sciss/Mellite#59]
a space too much between ":" and "=" in line:

scalaVersion in ThisBuild : = "2.12.2"

correct:
scalaVersion in ThisBuild := "2.12.2"

**Comment by Sciss** [comment]
Thank you for the report; I had this fixed in the 'work' branch, and merged back into master now. It's a bit unfortunate to have both the software and the site project in the same repository, perhaps I will find a better solution in the future.
